name: Yoloyi GitHub Page Deploy

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**-draft.md'
      - '**.png'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'
          extended: true

      - name: Build Hugo
        run: |
          HUGO_ENV=production hugo --gc --minify
          cp ./CNAME ./public/CNAME
          cp ./baidu_verify_6GkDhoZ3Pq.html ./public/baidu_verify_6GkDhoZ3Pq.html

      - name: Deploy Hugo to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
